name: PoishiisPP
version: '${project.version}'
main: poishiispp.poishiispp.PoishiisPP
api-version: 1.19
commands:
  toggleohko:
    description: Entities onehit you.
    usage: /toggleohko
    aliases: ohko
    default: true
  everythingKills:
    description: EVERYTHING onehits you.
    usage: /everythingkills
    default: true